;;; source_context.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))
  (sb-ext:muffle-conditions sb-kernel:redefinition-with-defun)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'source_context
    :syntax :proto3

    :package "google.protobuf")
)


;;; Top-Level messages

(pi:define-message source-context
    ()
  ;; Fields
  (file-name
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "fileName"))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"source_context.proto" 'source_context)
)

(cl:export '(file-name
source-context
source_context))
